# POST http://localhost:5000/auth/register
# content-type: application/json

# {
#     "username": "alibtd0",
#     "email": "ali3@gmail.com",
#     "password":"123456",
#     "profileImage":"https://fsdf.com"
# }


# POST http://localhost:5000/userInfo
# content-type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNocmlzQGdtYWlsLmNvbSIsInVpZCI6NDksImlhdCI6MTY0MjUzMzg3MCwiZXhwIjoxNjQzMzk3ODcwfQ.3flPjarJ5kUb8FdW_PGnh3ICRABjAEFLXkBHdQkKpzg



POST http://localhost:5000/addProfileImage
content-type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNocmlzQGdtYWlsLmNvbSIsInVpZCI6NDksImlhdCI6MTY0MjUzMzg3MCwiZXhwIjoxNjQzMzk3ODcwfQ.3flPjarJ5kUb8FdW_PGnh3ICRABjAEFLXkBHdQkKpzg