# POST http://localhost:5000/auth/register
# content-type: application/json

# {
#     "username": "alibtd0",
#     "email": "ali3@gmail.com",
#     "password":"123456",
#     "profileImage":"https://fsdf.com"
# }


# POST http://localhost:5000/userInfo
# content-type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNocmlzQGdtYWlsLmNvbSIsInVpZCI6NDksImlhdCI6MTY0MjUzMzg3MCwiZXhwIjoxNjQzMzk3ODcwfQ.3flPjarJ5kUb8FdW_PGnh3ICRABjAEFLXkBHdQkKpzg



# POST http://localhost:5000/addProfileImage
# content-type: application/json
# Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNocmlzQGdtYWlsLmNvbSIsInVpZCI6NDksImlhdCI6MTY0MjUzMzg3MCwiZXhwIjoxNjQzMzk3ODcwfQ.3flPjarJ5kUb8FdW_PGnh3ICRABjAEFLXkBHdQkKpzg

POST https://www.fileconverto.com/video-compressor/
content-type: multipart/form-data; boundary=----WebKitFormBoundarygbic4LQ6x9qVsGRw
cookie: cookiebanner-accepted=1
origin: https://www.fileconverto.com
referer: https://www.fileconverto.com/video-compressor/
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9

{

}